---
- name: Linux Patching | Install Packages | Enable Multilib
  ini_file:
    path: /etc/pacman.conf
    section: multilib
    option: Include
    value: /etc/pacman.d/mirrorlist

- name: Linux Patching | Install Packages | Enable Parallels Download
  ini_file:
    path: /etc/pacman.conf
    section: options
    option: ParallelDownloads
    value: '10'

- name: Linux Patching | Install Packages | Upgrade existing all packages in Archlinux
  pacman:
    state: latest
    update_cache: true
  register: rv_linux_patching_patch_state
  when:
    - rv_linux_patching_upgrade_existing_packages is defined and rv_linux_patching_upgrade_existing_packages != None
    - rv_linux_patching_upgrade_existing_packages

- name: Linux Patching | Install Packages | Install specific essential packages in Archlinux
  pacman:
    name: "{{  rv_linux_patching_packages_Archlinux  }}"
    state: present
  when: rv_linux_patching_packages_Archlinux is defined
