---
- name: Linux Patching | Setup Host Date Time | Set timezone as {{  rv_linux_patching_timezone  }}
  timezone:
    name: "{{  rv_linux_patching_timezone  }}"
    hwclock: local

- name: Linux Patching | Setup Host Date Time | Ensure a locale exists as en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Linux Patching | Setup Host Date Time | Ensure a locale exists as en_US.UTF-8 for Archlinux
  lineinfile:
    dest: "{{  item.file  }}"
    owner: root
    group: root
    line: "{{  item.line  }}"
    state: present
    create: yes
  with_items:
    - file: /etc/locale.gen
      line: en_US.UTF-8 UTF-8
    - file: /etc/locale.conf
      line: LANG=en_US.UTF-8
  when: ansible_distribution == 'Archlinux'
  register: rv_linux_patching_tmp_new_locale_updated_archlinux

- name: Linux Patching | Setup Host Date Time | locale-gen for Archlinux
  shell: locale-gen
  when: rv_linux_patching_tmp_new_locale_updated_archlinux["changed"]
