---
- name: Linux Patching | Setup Host Date Time | Checking Prerequisite
  block:
    - name: Linux Patching | Setup Host Date Time | Checking Prerequisite | Include Common Checks
      include_tasks: prerequisite.yml

- name: Linux Patching | Setup Host Date Time | Set timezone as {{  rv_linux_patching_timezone  }}
  timezone:
    name: "{{  rv_linux_patching_timezone  }}"
    hwclock: local
  ignore_errors: true
  register: rv_linux_patching_hw_settime_result

- name: Linux Patching | Setup Host Date Time | Set timezone as {{  rv_linux_patching_timezone  }} via softlink
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ rv_linux_patching_timezone }}"
    dest: /etc/localtime
    state: link
  when: rv_linux_patching_hw_settime_result.failed

- name: Linux Patching | Setup Host Date Time | Ensure a locale exists as en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present
  environment:
    PATH: /usr/sbin:{{ ansible_env.PATH }}
