---
- name: Linux Patching | Network | Checking Prerequisite
  block:
    - name: Linux Patching | Network | Checking Prerequisite | Include Common Checks
      include_tasks: prerequisite.yml

- name: Linux Patching | Network | Make sure the folder exists
  file:
    path: "{{  rv_linux_patching_ca_certificate_dir  }}"
    state: directory

- name: Linux Patching | Network | Disable Wifi MAC randomization
  community.general.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_items:
    - { section: "device", option: "wifi.scan-rand-mac-address", value: "no"  }
    - { section: "device-mac-randomization", option: "wifi.scan-rand-mac-address", value: "no"  }
    - { section: "ifupdown", option: "managed", value: "true"  }

- name: Linux Patching | Network | Copy the certificate
  copy:
    src: "files/cert.pem"
    dest: "{{  rv_linux_patching_ca_certificate_dir  }}/cert.crt"
  register: rv_linux_patching_copy_crt_tmp_result

- name: Linux Patching | Network | Update CA Trust
  command: "{{  rv_linux_patching_ca_certificate_update_shell  }}"
  when: rv_linux_patching_copy_crt_tmp_result.changed

- name: Linux Patching | Network | Set iptables to iptables legacy
  alternatives:
    name: iptables
    link: /usr/sbin/iptables
    path: /usr/sbin/iptables-legacy

- name: Linux Patching | Network | Set ip6tables to iptables legacy
  alternatives:
    name: ip6tables
    link: /usr/sbin/ip6tables
    path: /usr/sbin/ip6tables-legacy

- name: Linux Patching | Network | Setup Host Network Information | Set Host-Name
  hostname:
    name: "{{  rv_linux_patching_hostname_fqdn  }}"
  when:
    - rv_linux_patching_hostname_fqdn is defined
    - rv_linux_patching_hostname_fqdn != ""

- name: Linux Patching | Network | Setup Host Network Information | Set loopback and host IP
  lineinfile:
    dest: /etc/hosts
    mode: "0644"
    line: "{{  item.line  }}"
    regexp: "{{  item.regexp  | default(omit)  }}"
    state: present
    create: yes
  with_items:
    - line: "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4"
      regexp: "^127.0.0.1"
    #- line: "::1 localhost localhost.localdomain localhost6 localhost6.localdomain6 ip6-localhost ip6-loopback"
    #  regexp: '^::1'
    # - line: "127.0.1.1 {{  rv_linux_patching_hostname_fqdn  }} {{  rv_linux_patching_hostname_fqdn  }}.{{  rv_linux_patching_hostdomain  }}"
    #- line: "{{  rv_linux_patching_hostipv4  }} {{  rv_linux_patching_hostname_fqdn  }} {{  rv_linux_patching_hostname_fqdn  }}.{{  rv_linux_patching_hostdomain  }}"
  ignore_errors: true
  when:
    - rv_linux_patching_hostname_fqdn is defined
    - rv_linux_patching_hostdomain is defined
    - rv_linux_patching_hostname_fqdn != ""
    - rv_linux_patching_hostdomain != ""
    - false

- name: Linux Patching | Network | Setup Host Network Information | Enable network services
  service:
    name: "{{  item  }}"
    enabled: yes
  with_items: "{{  rv_linux_patching_net_time_services  }}"
