---
- name: Linux Patching | Install Packages | Checking Prerequisite
  block:
    - name: Linux Patching | Install Packages | Checking Prerequisite | Include Common Checks
      include_tasks: prerequisite.yml

- name: Linux Patching | Install Packages | Upgrade existing all packages in Debian
  apt:
    name: "*"
    state: latest
    update_cache: true
  when:
    - rv_linux_patching_upgrade_existing_packages

- name: Linux Patching | Install Packages | Install specific essential packages in Debian
  apt:
    name: "{{  rv_linux_patching_packages  }}"
    state: present
    update_cache: true
  when:
    - rv_linux_patching_packages is defined
    - rv_linux_patching_packages | length > 0

- name: Linux Patching | Install Packages | Install headers linux-headers-{{ansible_kernel}}
  apt:
    name: "linux-headers-{{ansible_kernel}}"
    state: present
    update_cache: true
  when: rv_linux_patching_install_headers
  ignore_errors: true
  register: rv_linux_patching_install_headers_tmp_kernel_version_installed

- name: Linux Patching | Install Packages | Install generic headers linux-headers
  apt:
    name: "linux-headers"
    state: present
    update_cache: true
  when: rv_linux_patching_install_headers_tmp_kernel_version_installed.failed
