---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - include_role:
        name: arpanrec.linux_patching
        tasks_from: datetime.yml

    - include_role:
        name: arpanrec.linux_patching
        tasks_from: packages.yml

    - include_role:
        name: arpanrec.linux_patching
        tasks_from: network.yml

    - include_role:
        name: arpanrec.linux_patching
        tasks_from: user.yml
