---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: meta/requirements.yml
driver:
  name: vagrant
  provider:
    name: vmware_workstation
platforms:
  - name: ubuntu
    box: sourceshift/ubuntu-20.04-amd64-efi
    memory: 4096
    cpus: 4
    box_version: 1.0.0
    provider_options:
      gui: True
provisioner:
  name: ansible
  vvv: true
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      vmware:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
