---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: ssh
      ansible_user: vmuser
      ansible_password: password
      ansible_sudo_pass: password
      ansible_ssh_common_args: -o StrictHostKeyChecking=no
platforms:
  - name: 172.16.184.138
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        sadasf: afsaf
scenario:
  name: default
  test_sequence:
    - converge
    - side_effect
    - verify
verifier:
  name: ansible
  lint:
    name: ansible-lint
