---
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
driver:
  name: delegated
  provider:
    managed: false
    ansible_connection_options:
      ansible_python_interpreter: /usr/bin/python3
      ansible_connection: ssh
platforms:
  - name: debian11
provisioner:
  name: ansible
  vvv: true
  playbooks:
    converge: ../common/converge.yml
  inventory:
    host_vars:
      debian11:
        ansible_host: 192.168.0.163
        ansible_port: 22
        ansible_user: pi
        ansible_password: pi
        ansible_become_password: pi
        ansible_become_method: sudo
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        rv_linux_patching_hostname_fqdn: rb4-m1
scenario:
  converge_sequence:
    - converge
  test_sequence:
    - lint
    - syntax
    - converge
    - idempotence
    - side_effect
verifier:
  name: ansible
